#!/bin/bash
#NOM    : Demo
#CLASSE : ED - LaboED 02-01
#OBJET  : réservé au makefile
#AUTEUR	: J.C. Jaumain, 07/2011
C='\033[44m'
E='\033[32m\033[1m'
W='\033[31m\033[1m'
N='\033[0m'
clear
echo "Démonstration du programme ContenuInode"
echo "---------------------------------------"
echo
echo -n "Fichiers du répertoire courant : "
ls
echo "---------------------------------------"
echo -n "Donnez un nom de fichier de ce répertoire : "
read fichier
echo -e "Éxecution de ${E}./ContenuInode $fichier${N} :"
./ContenuInode $fichier
if [ $? -eq 0 ]
then
echo "---------------------------------------------- "
echo "Vérification sur base des commandes ls et du : "
echo "     Mise en forme avec la commande awk "
echo "---------------------------------------------- "
echo -n "Numero d'inode = "; ls -i $fichier | awk '{print $1}'
echo -n "Nombre de liens hardware = "; ls -n $fichier | awk '{print $2}'
echo -n "Propriétaire du fichier = "; ls -n $fichier | awk '{print $3}'
echo -n "Groupe du propriétaire du fichier = "; ls -n $fichier | awk '{print $4}'
echo -n "Taille du fichier = "; ls -n $fichier | awk '{print $5}'
echo -n "Taille sur disque = "; du -h $fichier | awk '{print $1}'
echo -e "${C}             --> Enter pour continuer${N}"
read
else
echo -e "${W}Le programme ContenuInode a décelé une erreur"
echo -e "Probablement, le nom de fichier que vous avez donné"
echo -e "n'existe pas dans le répertoire courant${N}" 
echo -e "${C}             --> Enter pour continuer${N}"
read
fi
