#NOM    : Makefile
#CLASSE : Process - LaboProcess 03-01
#OBJET  : demo du programme cg
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011

cg: cg.c 
	#gcc cg.c -o cg
	gcc -std=c99 -Wall -pedantic-errors cg.c -o cg

clean:
	rm -f cg aff *~
