#NOM    : Makefile
#CLASSE : Process - LaboProcess 02-01
#OBJET  : demo du programme Wait4
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011

Wait4: Wait4.c 
	gcc -std=c99 -Wall -pedantic-errors -D_BSD_SOURCE Wait4.c -o Wait4 -lm

clean:
	rm -f Wait4 *~
