#!/bin/bash
#NOM    : Demo
#CLASSE : ED - LaboED 04-01
#OBJET  : réservé au makefile
#AUTEUR	: J.C. Jaumain, 07/2011
clear
C='\033[44m'
E='\033[32m\033[1m'
W='\033[31m\033[1m'
N='\033[0m'
clear
echo "Démonstration du partitionnement du disk"
echo "----------------------------------------"
echo
if [ $(id -u) -ne 0 ] # si pas administrateur
then 
	echo "Vous devez être administrateur pour lire un tel périphérique"
	echo
	echo -e "${C}             --> Enter pour continuer${N}"
	read
	exit 0
fi

echo "Insérez la clé USB"
echo
echo -e "${C}             --> Enter pour continuer${N}"
read
sleep 1
echo -e "${E}résultat de dmesg${N}"
echo
dmesg | tail
echo
echo -e "${E}résultat de lsblk${N}"
echo
lsblk
echo
echo -n -e "${E}Entrez le nom du device à lire (exemple /dev/sdj,...): ${N}"
read device
echo
echo
echo -e "${E}résultat de fdisk -l $device ${N}"
echo
fdisk -l $device
echo
echo
echo -e "${C}             --> Enter pour continuer${N}"
read
echo -e "${E}résultat de LectGPT $device ${N}"
echo
./guid_reader.o $device
echo
echo -e "${C}             --> Enter pour continuer${N}"
read

