#!/bin/bash

C='\033[44m'
E='\033[32m\033[1m'
N='\033[0m'
clear
echo "Démonstration du programme producer.c / consumer.c"
echo "------------------------------------"
echo -e "Exécution de ${E}du makefile${N}"
make all
echo -e "Exécution de ${E}./cons&${N}"
./consumer&
echo -e "\nExécution de ${E}./prod${N}"
./producer