#NOM    : Makefile
#CLASSE : Process - LaboProcess 05-02
#OBJET  : demo du programme PipeShellErr.c
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011

PipeShellErr: PipeShellErr.c 
	gcc -std=c99 -Wall -pedantic-errors PipeShellErr.c -o PipeShellErr

clean:
	rm -f PipeShellErr fichier *~
