#NOM    : Makefile
#CLASSE : ED - LaboED 02-01
#OBJET  : demo du programme ContenuInode
#HOWTO	: make; make clean
#AUTEUR	: J.C. Jaumain, 07/2011


ContenuInode: ContenuInode.c 
	gcc -std=gnu99 -Wall ContenuInode.c -o ContenuInode

clean:
	rm -f ContenuInode fichier *~
